[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = ["https://sc-groupomania.netlify.app", "https://groupomania.stephane-chimy.com]